### ISSUE TITLE
2.2 regression is breaking Travis tests

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-postgresql#95] opened 2019-04-20 23:06 UTC
See https://travis-ci.org/silverstripe/silverstripe-installer/jobs/522590101

Example error:

```
SELECT DISTINCT "ClassName", "SiteTree"."ID", "ParentID", "Title", "URLSegment", "Content", "LastEdited", "Created", NULL AS "Name", "CanViewType", ts_rank("SiteTree"."ts_SearchFields", q) AS "Relevance"
FROM "SiteTree" , to_tsquery('english', 'publicPublishedPage*') AS q AS "tsearch"
WHERE ("ShowInSearch" = $2)
 AND ("SiteTree"."ts_SearchFields" @@@ q )) AS q1 
ORDER BY "Relevance" DESC
LIMIT 10 OFFSET 0
ERROR:  syntax error at or near "AS"
LINE 2: ...o_tsquery('english', 'publicPublishedPage*') AS q AS "tsearc...
                                                             ^
```

# PRs
- [x] silverstripe/silverstripe-framework#8956
- [x] silverstripe/silverstripe-framework#8966
- [x] https://github.com/silverstripe/silverstripe-postgresql/pull/97

**Comment by ScopeyNZ** [comment] 2019-04-30 03:44
Had a quick look at this. This is caused by a bugfix to framework:

https://github.com/silverstripe/silverstripe-framework/pull/8918

In `PostgreSQLDatabase`s implementation of `searchEngine` it adds a "from" table with an alias:

https://github.com/silverstripe/silverstripe-postgresql/blob/e0d55367154ae4f3fc30d0604277db4d20fa7478/code/PostgreSQLDatabase.php#L451

This was previously erroneously dropped - and it looks like the code caters for that by appending it's own alias. I _think_ this can be fixed by removing the key definition in that array

**Comment by dnsl48** [comment] 2019-05-01 22:48
That'd be a breaking change in APIs if we simply patch the PostgreSQLDatabase.
I reckon we need to spare the pre-existing behaviour and let postgres be unchanged at this point (potentially patch its master)

**Comment by ScopeyNZ** [comment] 2019-05-01 22:52
I disagree. Previously the `tsearch` key was completely ignored due to a bug. That query is not exposed so isn't consumed as part of public API. We can make changes to the building of that query without worrying about BC break.

It should just be a patch change that will be benign for all versions of framework before 4.4.

**Comment by dnsl48** [comment] 2019-05-01 22:58
> Previously the tsearch key was completely ignored due to a bug
does not really matter why it was ignored. That's API behaviour, which has been changed.
Here we've got a library (postgresql), which is using the API (::addFrom method). There may be other projects in the wild which rely on that behaviour, and they gonna get broken if we ignore that.

**Comment by ScopeyNZ** [comment] 2019-05-01 23:25
Ok the API break you're talking about is an already merged bug fix. If you're worried about it then maybe this should be raised on `silverstripe/framework`.

**Comment by dnsl48** [comment] 2019-05-02 21:35
Related PR: https://github.com/silverstripe/silverstripe-framework/pull/8956
(I don't have access to this repo to add it to the head post)

**Comment by robbieaverill** [comment] 2019-05-02 21:37
I’ve added your team with write access

**Comment by chillu** [comment] 2019-05-05 21:29
@dnsl48 PR is merged, can we close this ticket?

**Comment by robbieaverill** [comment] 2019-05-05 21:30
I've restarted the two CMS recipe builds that remain broken due to this issue: https://travis-ci.org/silverstripe/recipe-cms/builds/522868872 https://travis-ci.org/silverstripe/recipe-cms/builds/522869053. I think we can close the issue though

**Comment by ScopeyNZ** [comment] 2019-05-05 22:47
I think we should still have a PR to resolve the bad code in this repo so I'll re-open this issue.

The aforementioned code (https://github.com/silverstripe/silverstripe-postgresql/blob/e0d55367154ae4f3fc30d0604277db4d20fa7478/code/PostgreSQLDatabase.php#L451) still has a bug that's double-aliasing. The framework "fix" just offered some BC for code that relied on the bug.

**Comment by dnsl48** [comment] 2019-05-05 22:53
Yes, agree. Ideally we have 2 more PRs:
 - to remove the BC FIX from the next major
 - to fix the alias dissonance

**Comment by dnsl48** [comment] 2019-05-06 04:29
added the PRs to the head post

**Comment by dnsl48** [comment] 2019-05-09 00:39
All done.

**Closed by dnsl48** 2019-05-09 00:39 UTC
Labels: affects/v4, change/patch, effort/medium, impact/high, type/bug
